### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by AnonHexo** [1nVitr0/plugin-vscode-censitive#1]
I have extension installed, a file named `.censitive` which contains this: `*.{js,ts}:apitoken,.*password`.
Then i have in my `index.js` file: `const config = {
    secretPassword: "ciao1234",
}` but nothing get censored...

![image](https://user-images.githubusercontent.com/61375258/111084706-08e50900-8514-11eb-8470-4770fb805efe.png)
![image](https://user-images.githubusercontent.com/61375258/111084718-13070780-8514-11eb-8ece-a610de6d0994.png)

**Comment by AnonHexo** [comment]
I just restarted vscode and fixed everything... 
Great Work man!

**Comment by 1nVitr0** [comment]
It should start automatically, but maybe vscode has some issues registering the file. I'll investigate, wanted work on it anyway

**Comment by 1nVitr0** [comment]
Is a result of https://github.com/microsoft/vscode/issues/28122, vscode doesn't trigger activation on file name changes.
