### ISSUE TITLE
Where to place .censitive to apply to all files (saved or not) without a workspace

### ISSUE THREAD

**Issue by lavermil** [1nVitr0/plugin-vscode-censitive#16]
Hello,

I am trying to find where to put the .censitive file for global settings. For example I want to use a default for all files and not just a specific workspace.

In Linux the settings.json file is in ~/.config/Code/User/. I thought I would place it in the same folder but apparently that is not correct. I have also tried putting it in ~/.vscode/.

I can make it work for an single or multiple workspaces.

**Comment by 1nVitr0** [comment]
@lavermil A `.censitive` file in yout home directory should now be applied to all workspaces. Keep in mind, that the `glob` pattern is still applied relative to the workspace root, so opening files outside the workspace might not get censored as expected. To include any files of a pattern, prefix it with `**/`:

```censitive
**/.env:.*token,.*password
```

If you have any issues let me know. This Update also removes the need to relaod the window after a `.censitive` file is added to the workspace, as the extension is now always active.

**Comment by 1nVitr0** [comment]
There still seems to be a need for reloading the window when changing the `.censitive` file in the home directory. Not sure when I'll get around to fixing that. The file is probably not changing that often, so it's not at the top of my priority list.

**Comment by lavermil** [comment]
Thx for the update. Appreciate your good work!

**Comment by BakersSquare** [comment]
I've placed a .censitive file in my C:/Users/[user] directory with globs I'd like to censor. Is Windows supposed to be supported with this fix? I'm on Windows 10 x64

**Comment by 1nVitr0** [comment]
@BakersSquare It is, though I have not personally tested it. The implementation does not look correct to me, though I'm sure I did my research when implementing this. If you have the time, feel free to open an issue for this, though it might take me a while, I currently have a lot of personal stuff on my plate.
