### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by teisseire117** [1nVitr0/plugin-vscode-censitive#19]
Hello,
My .censitive : 
```python
// Format <globPattern>:[keyRegex]
.env:.*_KEY,.*_token,.*_PassWord
id_rsa:*
*.{py}:password
```

variable did not get hidden : 
![ZwRZVDH](https://user-images.githubusercontent.com/43145883/207770967-c03fbed5-8959-4d16-a70f-be7f48888118.png)

I tried Reload window, I tried Restarting VSCode.
I put the .censitive at the root of my workspace, I also tried putting it in C:\Users\HiImUser1, and also tried putting it in the folder where the credentials.py is.
Am I doing it wrong ? Is C:\Users\x the right place for global config ?

Here is config in VSCode : 
![wn0srui](https://user-images.githubusercontent.com/43145883/207771287-c57db340-9da1-4faf-af9f-090b79df0c51.png)
![aoOJwb6](https://user-images.githubusercontent.com/43145883/207771344-2a84e2a7-4b62-4300-8650-38e4d63abbed.png)

**Comment by 1nVitr0** [comment]
Sorry for the late response. Your configuration looks fine to me, might be some issue with python syntax.

Will get back to you once I figure that out.

**Comment by 1nVitr0** [comment]
@teisseire117 It should be working. When testing the setup you described, python files get censored as configured. I assume you are on Windows, judging by the path examples you provided?

`C:\Users\[YOUR_URSERNAME]` is correct for the global config, although I tend to mainly test on Linux. I will test on Windows tomorrow, athough there should be no difference in VSCode API.

**Comment by teisseire117** [comment]
> @teisseire117 It should be working. When testing the setup you described, python files get censored as configured. I assume you are on Windows, judging by the path examples you provided?
> 
> `C:\Users\[YOUR_URSERNAME]` is correct for the global config, although I tend to mainly test on Linux. I will test on Windows tomorrow, athough there should be no difference in VSCode API.

Yes I'm on Window 10. I retried today but I don't know it doesn't change anything

**Comment by 1nVitr0** [comment]
Ahh. I think I see what your issue is. I tested only for a configuration file in the workspace root based on your configuration. To inlcude files in subfolders, you must prefix the `glob` with `**/` (all folders). So changing your configuration to

```
**/*.{py}:password
```

should do the trick. Although I would recommend limiting the glob to a specific subfolder to improve performance.

**Comment by teisseire117** [comment]
> Ahh. I think I see what your issue is. I tested only for a configuration file in the workspace root based on your configuration. To inlcude files in subfolders, you must prefix the `glob` with `**/` (all folders and subfolders). So changing your configuration to
> 
> ```
> **/*.{py}:password
> ```
> 
> should do the trick. Although I would recommend limiting the glob to a specific subfolder to improve performance.

Yup, it worked <3
