### ISSUE TITLE
Publish to OpenVSX?

### ISSUE THREAD

**Issue by xdevc512l** [1nVitr0/plugin-vscode-censitive#22]
OpenVSX is an open-source marketplace alternative to the Visual Studio Marketplace. It would be great to have the extension also available on other vscode-based editors like [VSCodium](https://vscodium.com/) or [Theia](https://theia-ide.org/).

**Comment by 1nVitr0** [comment]
Should be done now. Thanks for the reminder, had been planning this for a while...
