### ISSUE TITLE
[Enhancement] Support `.censitive` files in subdirectories

### ISSUE THREAD

**Issue by Rooika** [1nVitr0/plugin-vscode-censitive#31]
Hello,

I followed the guide line and I think I did something wrong but I don't where.
Could you help me ? 

The .censitive file and .env are in the same folder in my workspace (I tried also with the .censitive in the workspace folder directly but doesn't work). I used the "Developper : Reload Window" and I've also closed and reopen VSCcode).

Any clue ?

Could you tell me also why the "." before each keyword ?

![image](https://user-images.githubusercontent.com/131373542/233383807-3902c28c-4479-4066-9353-b0abe17002fd.png)

![image](https://user-images.githubusercontent.com/131373542/233383932-03dd0b4b-7652-4656-8049-d86be1a1f2ea.png)

![image](https://user-images.githubusercontent.com/131373542/233384078-d481375f-ab43-4eb1-8be9-39dfac75afe3.png)

Thank in advance :)

**Comment by 1nVitr0** [comment]
It looks to me like your `.censitive` file is not in the workspace root, but in a subfolder (unless you have multiple workspaces open.

For some reason I have never thought about that, it should totally be possible. For now, try moving your file into the workspace root.

**Comment by Rooika** [comment]
Hello,

I moved the .censitive file to the workspace root (if I've well understood "where" is the workspace root (see the screenshot :P )) but the problem is still present :/

I've reload the UI and I've also restarted VSC


![image](https://user-images.githubusercontent.com/131373542/233915378-0450f403-9f6e-4580-9bfd-8a02fd5b60f7.png)

**Comment by Rooika** [comment]
And all the extension settings are enabled : 

![image](https://user-images.githubusercontent.com/131373542/233915954-1a4adfac-bd3a-4928-841c-e9fbb7517cce.png)

**Comment by 1nVitr0** [comment]
Yep, that's definitely the workspace root. You're on Windows?

**Comment by Rooika** [comment]
Yep, I'm :)

**Comment by 1nVitr0** [comment]
Ahh, I think I see it, sorry for the confusion. If I haven't implemented it weirdly, the `glob` is relative to the workspace root. So `.env` only matches `.env` files,  that are directly in the root directory.

Can you try `**/.env` instead? That should match any `.env` files in any subdirectories.

**Comment by Rooika** [comment]
Ahhhhh
Its works !!!

Thank a lot for your help :D
