### ISSUE TITLE
Provide a regex way of identifying secrets

### ISSUE THREAD

**Issue by Murazaki** [1nVitr0/plugin-vscode-censitive#33]
Hi, I would like to be able to hide certificate and the like, is there a way to call our own regex match ?

```regex
**/*.{pem,crt,key}:-+BEGIN (CERTIFICATE|RSA PRIVATE KEY|PRIVATE KEY)-+\n(.*)+?\n-+END (CERTIFICATE|RSA PRIVATE KEY|PRIVATE KEY)-+
```

**Comment by 1nVitr0** [comment]
I went against enabling custom regexes to avoid both performance issues, that re not caused directly by the extension, as well as provide an easy way to supply keys to censor. There is a lot of space-and-newline-ignoring and line ending support going on behind the scenes. There already is the option to censor the entire file by providing `*` as the censoring key, which might be enough in this case:

```censitive
**/*.{pem,crt,key}:*
```

But I'll look into supporting fencing operators such as `BEGIN [...]` `END [..]`.
