### ISSUE TITLE
Missing censor pattern for old ruby 'hash rocket'

### ISSUE THREAD

**Issue by Murazaki** [1nVitr0/plugin-vscode-censitive#34]
Censoring doesn't work on old syntax hash rocket in ruby files :

```ruby
config['values'] = {
'subgroup' => {
  'uid' => 'user',
  'password' => 'sosecret',
  }
}
```

**Comment by 1nVitr0** [comment]
Didn't know such an operator existed. But while I was at it, this would've also been an issue for PHP.

**Comment by 1nVitr0** [comment]
Will release it today, after I went through the other pull request
