### ISSUE TITLE
Lock icons and blockers inserted everywhere on edit

### ISSUE THREAD

**Issue by daniel-mmm** [1nVitr0/plugin-vscode-censitive#39]
I am getting an error where lock icons and blockers are inserted on every road instead of only the row intended.

When editing the file more locks and blockers are inserted into the file for every key press.

This makes the extension unusable

I see this in the developer console:

----

`console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'setCensoredRanges')
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:862
deliver @ event.ts:1075
fire @ event.ts:1031
fire @ ipc.net.ts:671
ee.onmessage @ localProcessExtensionHost.ts:583

console.ts:137 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'setCensoredRanges')
	at d.applyCensoredRanges (/home/danielm/.vscode/extensions/1nvitr0.censitive-1.3.0/dist/extension.js:1:8497)
	at d.<anonymous> (/home/danielm/.vscode/extensions/1nvitr0.censitive-1.3.0/dist/extension.js:1:10335)
	at Generator.next (<anonymous>)
	at r (/home/danielm/.vscode/extensions/1nvitr0.censitive-1.3.0/dist/extension.js:1:5586)
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:862
deliver @ event.ts:1075
fire @ event.ts:1031
fire @ ipc.net.ts:671
ee.onmessage @ localProcessExtensionHost.ts:583

mainThreadExtensionService.ts:81 [1nVitr0.censitive]Cannot read properties of undefined (reading 'setCensoredRanges')
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:862
deliver @ event.ts:1075
fire @ event.ts:1031
fire @ ipc.net.ts:671
ee.onmessage @ localProcessExtensionHost.ts:583

mainThreadExtensionService.ts:82 TypeError: Cannot read properties of undefined (reading 'setCensoredRanges')
	at d.applyCensoredRanges (vscode-file://vscode-app/home/danielm/.vscode/extensions/1nvitr0.censitive-1.3.0/dist/extension.js:1:8497)
	at d.<anonymous> (vscode-file://vscode-app/home/danielm/.vscode/extensions/1nvitr0.censitive-1.3.0/dist/extension.js:1:10335)
	at Generator.next (<anonymous>)
	at r (vscode-file://vscode-app/home/danielm/.vscode/extensions/1nvitr0.censitive-1.3.0/dist/extension.js:1:5586)`

----

I'm using:

Ubuntu 22.04.2 LTS

Code version:
Version: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:28:44.251Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-73-generic snap

**Comment by Rooika** [comment]
Hey,
I've the same issue from this morning.
The issue happens when VSCode is restarted.

To "solve" temporarily that, I changed the .censitive file to only take in care specifics files to not disturb files that I don't need to have this plugin, but it's not a good solution if I need to work within these specific files.

**Comment by daniel-mmm** [comment]
Tested now and seems to work :+1: :rocket: 
Thank you! :smiley:
