### ISSUE TITLE
Support pulling .censitive rules from User Settings

### ISSUE THREAD

**Issue by BakersSquare** [1nVitr0/plugin-vscode-censitive#42]
I think this extension would have a lot of flexibility if it could pull rules from the user settings instead of just the repository's .censitive file.

Some rule like ```"censitive.globalTerms"``` or ```"censitive.enableUserLevelCensoring"``` so that we don't have to configure .censitive files for each project in our workspace. I think this would add benefit users in a commercial or public setting too - so any instance where they're typing a pattern like ```"pattern"(:|=|-) [key]```, they could be protected even if not in a configured environment.

**Comment by BakersSquare** [comment]
I can play around with this - but am wondering if this was avoided on purpose or what others' thoughts are about it. Also would like to verify the longevity of the repo before contributing (not assuming that it's dead, but it has been nearly a year since the last release)

**Comment by 1nVitr0** [comment]
@BakersSquare The idea behind the `.censitive` file was to make it part of the git repository and open the possibility to transfer the functionality to other editors.

I do agree that integrating it to vscode's settings would be helpful, especially when considering syncing settings between machines. I will have to think on how to best transfer the syntax from `.censitive` files into settings. We'll also need some kind of merging logic between local / global `.censitive` settings and vscode settings.

I'll have to address an open issue in another extension first, then I will concentrate on this. Expect about 1-2 weeks before I get started on this.

**Comment by BakersSquare** [comment]
@1nVitr0 I see the reason for integrating the .censitive file into the git repository, but believe it to be most applicable for small teams. I'm installing the extension on my commercial system, and don't have as much control over these big repositories. You've created the option to store the .censitive file within the user's Home directory as a way to accommodate for repository restrictions like this, which was a very good idea.

I left a comment on this issue (#16 ) saying that this .censitive file configuration wasn't working for me, to which I suggested they also pull from the VSCode user settings. My assumption with this was that it would be easy to implement, and would be more native to the extension than reading from an offloaded file. I opened up my own branch to experiment with the rules myself, but spent time debugging and realized I just configured my .censitive file wrong.

Ultimately - I think the extension provides a lot of value in the state that it's in, and spending time on this improvement will yield little gain comparative to the effort. Even without the improvement, syncing settings between work stations will only take a few extra seconds while the user adds/modifies another .censitive file, which likely will not happen often.

I'll close this issue out as 'Wont Fix', as the Home directory .censitive file accomplishes the exact goal. Thanks for all your work on this extension, it's awesome.

**Comment by 1nVitr0** [comment]
@BakersSquare Just to let you know, there will be a `defaultCensoring` config in the next release. The primary objective for this was to enable zero-config censoring on intial extension install. Currently this equates to a `.censitive` file in the home directory containing:

```.censitive
**/{env,.env,env.*,.env.*}!**/{env.example,.env.example}:.*password,.*token,.*secret.*
**/id_{rsa,dsa,ecdsa,eddsa,dss,sha2}:-----BEGIN.*PRIVATE KEY-----:-----END.*PRIVATE KEY-----
```

If you (or anyone else) have any suggestions on what else should be included by default, feel free to write them here. This release also adds the ability to exclude globs from censoring usin `!<globPatter>` (described in README).
