### ISSUE TITLE
Default censoring settings doesn't work

### ISSUE THREAD

**Issue by daniel-mmm** [1nVitr0/plugin-vscode-censitive#55]
If I add a .censitive file to my workspace folder it works.

But I can't get censitive.defaultCensoring setting to work anymore. It worked previously but has stopped working without changing the settings.

A global .censitive file in my home directory doesn't work either.

I'm using windows and wsl. I have tried both in a windows folder directly and inside a wsl folder.

**Comment by 1nVitr0** [comment]
@daniel-mmm Might have broken that with the last update. Though I'm pretty sure I tested the `.censitive` file in the home directory quite thoroughly. Should be a fairly easy fix though

**Comment by 1nVitr0** [comment]
@daniel-mmm Just checking since you are actively using the extension. Are you experiencing higher than normal CPU and RAM usage since the update? Might be a different cause, but I have had issues roughly since my last update.

**Comment by daniel-mmm** [comment]
@1nVitr0 thanks for the response and checking to fix it.
I've recently changed computer so can't say that I've noticed any change in performance. Haven't thought about it either 🙂

**Comment by 1nVitr0** [comment]
@daniel-mmm The latest release fixed the issue for me, though I'm on pure linux and wasn't able to comprehensively test it. Definitely time for me to set up some automated tests.
