### ISSUE TITLE
Support for #define

### ISSUE THREAD

**Issue by Arubinu** [1nVitr0/plugin-vscode-censitive#57]
Is it possible to add support for C/C++ preprocessor definitions?

![image](https://github.com/user-attachments/assets/8bd9c46d-3017-4ad6-be9d-0a5908d42f02)

Since I discovered the plugin I was wondering why it never worked, but it's only because it's a case that is not taken into account.

**Comment by 1nVitr0** [comment]
@Arubinu Just in case you had overridden the `censitive.assignmentRegex` setting, you will have to merge the new default settings:

```json
{
    "censitive.assignmentRegex": {
          "default": "[\\t ]*[:=][=>]?[\\t ]*",
          "yaml": "[\\t ]*:[\\t ]*(?!>|\\|)",
          "cpp": "(?:[\\t ]*=[\\t ]*|(?<=^#define[\\t ]+.+)[\\t ]+)",
          "c": "(?:[\\t ]*=[\\t ]*|(?<=^#define[\\t ]+.+)[\\t ]+)"
      },
}
```

If you haven't it should just work with the next update.

**Comment by Arubinu** [comment]
The update makes the plugin functional for this case.
Thanks a lot!
